### PR TITLE
[fix] few boxes are not correctly parsed

### PR DESCRIPTION
**Pull request by zevlg**
Need also to parse children boxes for AudioSampleEntry and VideoSampleEntry boxes

### CODE REVIEW

**Comment by zevlg** [comment]
oh, sorry the patch is not quite correct.

I was a little confused with this picture:

```
...
     !   !            `---stbl
     !   !               !    size: 1603
     !   !               !`---stsd
     !   !               !   !    size: 151
     !   !               !   !    version: 0
     !   !               !   !    flags: 0x000000
     !   !               !   !    entry count: 1
     !   !               !    `---avc1
     !   !               !            size: 135
     !   !               !            data reference index: 1
     !   !               !            width: 1280
     !   !               !            height: 720
     !   !               !            horizontal resolution: 0x00480000
     !   !               !            vertical resolution: 0x00480000
     !   !               !            frame count: 1
     !   !               !            compressor name: 
     !   !               !            depth: 24
     !   !               !`---avcC
     !   !               !        size: 49
     !   !               !`---stts
     !   !               !        size: 24
     !   !               !        version: 0
...

...
     !   !            `---stbl
     !   !               !    size: 1854
     !   !               !`---stsd
     !   !               !   !    size: 106
     !   !               !   !    version: 0
     !   !               !   !    flags: 0x000000
     !   !               !   !    entry count: 1
     !   !               !    `---mp4a
     !   !               !            size: 90
     !   !               !            data reference index: 1
     !   !               !            sample size: 16
     !   !               !            sample rate: 2890137600
     !   !               !`---esds
     !   !               !        size: 54
     !   !               !`---stts
     !   !               !        size: 24
     !   !               !        version: 0
     !   !               !        flags: 0x000000
     !   !               !        entry count: 1
     !   !               !        sample count: 119
     !   !               !        sample delta: 1024
     !   !               !`---stsc
...
```

`avcC` must be part of `avc1`, not `stbl`.  Also `esds` is part of `mp4a`, not `stbl`

So, I thought that parsing childs for `avc1` and `mp4a` would do the trick, but it did not

**Comment by amarghosh** [comment]
I'll check the box order.. meanwhile, if you can  share a short mp4 file to reproduce the issue, that would be nice.

**Comment by zevlg** [comment]
thanks, here is the file https://www.dropbox.com/s/12gvcna9sv2rsck/bear-1280x720.mp4

**Comment by amarghosh** [comment]
The issue was related to the consumed_bytes variable; it wasn't updated properly. I have pushed a fix. I confirmed that it handles both issues you flagged. With the new approach, derived boxes can set a flag to convert itself to a container.

**Comment by zevlg** [comment]
thanks, it does work

**Comment by amarghosh** [comment]
Closing

**Pull request closed without merging**
